Repository oscarbenjamin/protosym, pull requests merged in 2023-03, with the labels that each got.

#39 feat: add to_llvm_ir and lambdify
  noxfile.py
  poetry.lock
  pyproject.toml
  src/protosym/simplecas.py
  tests/test_simplecas.py
Labels: enhancement

#40 benchmarks: Create `benchmarks` directory with example differentiation benchmarks
  .flake8
  benchmarks/test_differentiation.py
  poetry.lock
  pyproject.toml
Labels: testing

#41 maint: bump dev dependencies
  .github/workflows/constraints.txt
  poetry.lock
  pyproject.toml
Labels: dependencies

#43 Add Sym as a superclass for Expr
  pyproject.toml
  src/protosym/core/evaluate.py
  src/protosym/core/exceptions.py
  src/protosym/core/sym.py
  src/protosym/simplecas.py
  tests/core/test_sym.py
  tests/test_simplecas.py
Labels: enhancement

#46 Add Matrix and lambdification of matrices
  noxfile.py
  src/protosym/core/sym.py
  src/protosym/simplecas.py
  tests/core/test_sym.py
  tests/test_simplecas.py
Labels: enhancement

#49 refactor(simplecas): split simplecas into modules in a package
  src/protosym/simplecas.py
  src/protosym/simplecas/__init__.py
  src/protosym/simplecas/exceptions.py
  src/protosym/simplecas/expr.py
  src/protosym/simplecas/functions.py
  src/protosym/simplecas/lambdification.py
  src/protosym/simplecas/matrix.py
  src/protosym/simplecas/sympy_conversions.py
  tests/test_simplecas.py
Labels: refactoring
